### ISSUE TITLE
Variables are not implicitly cast when calling a declared function

### ISSUE THREAD

**Issue by JosVerburg** [FontoXML/fontoxpath#114]
Seen in version 3.4.1

When passing a variable in the variables JSON object and using it in a function it requires an explicit cast.

Repro case (change is on line 5)
[Raises Error: XPTY0004](https://xpath.playground.fontoxml.com/?mode=1&variables=%7B%22var%22%3A+12%7D&xml=%3Cxml%2F%3E&xpath=declare+%25public+function+Q%7Bns%7Dtest%28%24input+as+xs%3Ainteger%29+as+xs%3Ainteger+%7B%0A%09%24input+%2B+1%0A%7D%3B%0A%0AQ%7Bns%7Dtest%28%24var%29)
[Fixed with explicit cast](https://xpath.playground.fontoxml.com/?mode=1&variables=%7B%22var%22%3A+12%7D&xml=%3Cxml%2F%3E&xpath=declare+%25public+function+Q%7Bns%7Dtest%28%24input+as+xs%3Ainteger%29+as+xs%3Ainteger+%7B%0A%09%24input+%2B+1%0A%7D%3B%0A%0AQ%7Bns%7Dtest%28%24var+cast+as+xs%3Ainteger%29)

**Comment by DrRataplan** [comment]
Note to self: this is a smaller reproducable case, without an XQuery dependency:

```xpath
function($a as xs:integer){$a + 1}(
xs:decimal(1)
)
```

The spec says the following over [function conversion](https://www.w3.org/TR/xpath-31/#id-function-conversion-rules): 
> For each numeric item in the atomic sequence that can be promoted to the expected atomic type using numeric promotion as described in B.1 Type Promotion, the promotion is done.

[Type promotion](https://www.w3.org/TR/xpath-31/#promotion) says this:

> Numeric type promotion:
> A value of type xs:float (or any type derived by restriction from xs:float) can be promoted to the type xs:double. The result is the xs:double value that is the same as the original value.
> A value of type xs:decimal (or any type derived by restriction from xs:decimal) can be promoted to either of the types xs:float or xs:double. The result of this promotion is created by casting the original value to the required type. This kind of promotion may cause loss of precision.

However, if the type promotion fails (as in our case), we should still do the [SequenceType matching](https://www.w3.org/TR/xpath-31/#dt-sequencetype-matching) to determine whether the argument is of the correct type.

Because `xs:decimal` is a supertype of `xs:integer`, the SequenceType matching should succeed. We are incorrect in throwing the error!

**Comment by DrRataplan** [comment]
Never mind, not all `xs:decimal`s are valid `xs:integer`s. We are correct in throwing. This is not a bug.

A sidenote, for variables, we currently use some custom logic for type translations. JSON numbers are translated to `xs:decimal`. If we want to make this behaviour more in line with a spec, we could use the ` [parse-json](https://www.w3.org/TR/xpath-functions-31/#func-parse-json) function for inspiration. This one says the following about type conversions:

> xs:double for a JSON number

We should align to that. We will still have errors, but the behaviour is a bit better to predict. I do not think this change will introduce new errors, or fix current ones, because the function conversion code already treats them the same.
