### ISSUE TITLE
Remove or replace a custom XPath function

### ISSUE THREAD

**Issue by mehmetscoskun** [FontoXML/fontoxpath#138]
We can register a custom XPath function but we do not have a way to remove or replace a custom XPath function. I need this feature for test purposes. Second registry of a custom xpath function is added to the end of registration array but when it is called, it always uses the first registration. It can be solved by replacing or removing or maybe prioritizing.

**Comment by DrRataplan** [comment]
Agreed, running multiple FontoXPath instances, each with their separate external function library should be supported. However, using global scope is always an antipattern. What I would rather suggest is the following:

Add an extra option to the `evaluateXPath*` and `registerXQueryModule` functions, called `externalFunctions`, which contains a set of the current `externalFunction` objects. This way, we can make external function registrations as local as possible and prevent polluting the global scope. These external function will only be available in the context of that module or XPath, not in modules imported by the said module.

```javascript
evaluateXPath(
  `(:optionally, to improve readability and to allow static analysis:
  declare function XXX:XXX (xs:boolean) as xs:integer? external; :)
  XXX:XXX(true())`,
  ...,
  {
   // Make XXX resolve to XXX
    namespaceResolver: (prefix) => prefix,
    externalFunctions: [..., {
      localName: XXX,
      namespaceURI: XXX,
      arguments: ['xs:boolean'],
      returnType: 'xs:integer?',
     callback: function(a){return a ? 123 : null}
}, ...]})
```

This way, we can store a global cache of functions in Fonto, instead of storing it in FontoXPath, improving testability. The Fonto codebase can add additional reregister/unregister logic.

How would you feel about this?

**Comment by JosVerburg** [comment]
If I'm correct than you proposal would make the externalFunctions passed in `registerXQueryModule` private functions which can only be used in that module (the module is likely to register a public function).

Am I correct in this?

**Comment by DrRataplan** [comment]
Correct, the following would become the best way to 'register' a custom XPath function:

```javascript
evaluateXPath(
  module namespace XXX = "XXX";
  declare %public function XXX:XXX (xs:boolean) as xs:integer? external;
  ...,
  {
    externalFunctions: [..., {
      localName: XXX,
      namespaceURI: XXX,
      arguments: ['xs:boolean'],
      returnType: 'xs:integer?',
     callback: function(a){return a ? 123 : null}
}, ...]})
```

We would still have a global module cache, but that's a problem for a later time.

**Comment by DrRataplan** [comment]
Covered in #248
