### ISSUE TITLE
Custom XPath functions that take in an xs:date or xs:dateTime do not get given a Javascript Date

### ISSUE THREAD

**Issue by ymor** [FontoXML/fontoxpath#155]
Example function:
```
registerCustomXPathFunction(
            'fn:days-from-date',
            ['xs:date'],
            'xs:integer',
            (context: any, date: Date) => {
                return Math.floor(date.getTime() / 8.64e7)
            })
```

> TypeError: date.getTime is not a function

It returns this instead:
`w {
        h: 1970,
        a: 1,
        j: 1,
        o: 0,
        V: 0,
        C: 0,
        sa: 0,
        O: null,
        type: 'xs:date' }`

**Comment by DrRataplan** [comment]
Hi Mark, good find, that's a bug!

The issue is in https://github.com/FontoXML/fontoxpath/blob/master/src/registerCustomXPathFunction.ts#L23. Over here, we are not doing any kind of type mapping whatsoever. We do some mapping over here: https://github.com/FontoXML/fontoxpath/blob/master/src/evaluateXPath.ts#L115, but we also plain ignore dates here.

Suggested approach:

 - Extract the [transformXPathItemToJavascriptObject](https://github.com/FontoXML/fontoxpath/blob/master/src/evaluateXPath.ts#L115) function to another file
 - Expand on it by supporting the datelike structures

Would you feel confident in making a pull-request for this? A lot has changed since your last PR, but the [contribution guides](https://github.com/FontoXML/fontoxpath/blob/master/CONTRIBUTING.md) are up-to-date.

Thanks for the issue!

**Comment by ymor** [comment]
No worries, happy to take a look! Thanks for the pointers.

**Comment by DrRataplan** [comment]
Hi Mark, did you manage to take a look at this issue yet? I would be happy to assist you if you'd like me to help!

**Comment by ymor** [comment]
Sorry been really busy at work and due to go on holiday soon! 
I managed to get this far: https://github.com/FontoXML/fontoxpath/compare/master...ymor:bugfix/%2311-custom-xpath-functions-javascript-parameter-types 

Still need to look at dateTime etc

**Comment by DrRataplan** [comment]
Cool! No problem!

I checked out the feature branch, and I see the bulk of the work is already done, nice! I think it might just be enough to expand on the `isSubTypeOf` condition in the `transformXPathItemToJavascriptObject.ts` to do an `or` over all of the DateTime related types. All of the date / time / dateTime / gDay / gMonth related types are actually instances of the class defined in `DateTime.ts` in the end.

Enjoy your holiday! If you'd like me to pick up the PR, just give me a shout!
