### ISSUE TITLE
Atomizing array(*) is not implemented

### ISSUE THREAD

**Issue by hubgit** [FontoXML/fontoxpath#206]
I have a Schematron file containing quite a few selectors that produce the error "Atomizing array(*) is not implemented."

Is this something it would be possible to add support for?

**Comment by DrRataplan** [comment]
Hi Alf,

Correct, we do not currently support atomizing arrays. This is primarily a historic reason: during initial development, we made a function 'atomize', accepting a single value and outputting a single value. The one-to-one relation holds most of the time (one element -> one xs:anyAtomicType, etc). The main place where this does not hold are arrays: one array -> a sequence of values.

Because Fonto has not run into this issue that often, it is not yet addressed. We have it on a backlog, but I can not promise this will be addressed in any short term.

However, this could be a great first (code-related) pull request! The main issue lies in [atomize.ts](https://github.com/FontoXML/fontoxpath/blob/master/src/expressions/dataTypes/atomize.ts) and its usages. Most of the current code already uses the [ISequence#atomize]( https://github.com/FontoXML/fontoxpath/blob/master/src/expressions/dataTypes/ISequence.ts#L49) function, which can be refactored to support sequence -> sequence atomization, but a quick search found about 27 more direct usages of the `atomize` function. Most of them should be able to also use the `ISequence#atomize` function, but I suspect some may need some more attention.

Would you feel confident in trying to properly implement array atomization? If you need any help on it, we are ready to assist you in any way!

**Comment by hubgit** [comment]
I've had [a go at this](https://github.com/hubgit/fontoxpath/commit/71c866f186db078c2d87e9ab2880bd0f9a33b243) but it's obviously not quite right, and I'm hitting the limits of my understanding of XQuery.

I've read the array section of https://www.w3.org/TR/xquery-31/#dt-atomization as "recursively atomize  the members of the array, then flatten the resulting array to produce a sequence".

I've used `flat` so added `es2019` to `lib` in tsconfig.ts, but there's a more verbose way of doing the same thing if needed.

`npm run build` complains about the use of `sequenceFactory` here, so maybe there's a better way to produce a sequence at the end?

**Comment by hubgit** [comment]
@DrRataplan With a bit more experience I've re-read your comment above and understand more of the problem. Would you say that it would never be appropriate for the `atomize` function to return a sequence, and that there should always be something higher up that takes a different path for arrays?

**Comment by DrRataplan** [comment]
Mostly correct,

I also took a go at this issue, I just pushed a branch with my changes, it's a bit rough but it should pass the related QT3 tests.

On a high level, I did the following: make atomization return sequences. The main datatype in XQuery / XPath is a sequence of values. atomization now accepts a sequence of items (items may be arrays containing new sequences). After that, I had a log of TypeScript errors because I was referencing values where I should use Sequences and vice versa.

I fixed most of the calls by using sequences, but for some of them, I just assumed the atomization process will only output a single value. Elements for instance always atomize to a single value if there is no type assigned to it.

I think I underestimated the complexity a bit, sorry for that. Thanks for having a go at it though!

Could you take a look at my PR and see whether I forgot something somewhere?

**Comment by hubgit** [comment]
Looks good! I can't vouch for the correctness or completeness of the changes, but it at least gets past the initial error that was the basis of this issue, with the XML sample that I'm validating.

**Comment by DrRataplan** [comment]
I have just integrated the pull request. Sorry it took a bit longer than anticipated. I'm planning to do a release somewhere this week; I'm hoping to get the matches function shipped at the same time

**Comment by DrRataplan** [comment]
Shipped in 3.10.0, Good luck with the rest of the Schematron files! Please report back if we can help you in any other way!
