### ISSUE TITLE
how to add functions?

### ISSUE THREAD

**Issue by JoernT** [FontoXML/fontoxpath#214]
First of all - fontoxpath is a great effort!

I'd really like to dive deeper and maybe even contribute one day. However documentation is a bit sparse. I'm seriously missing a bit more elaborated examples of e.g. how to add new functions. 

I just don't get it from only reading the sources. If you'd like to see contributions you have to help it i fear (being myself an open source developer for many years) - is there any place where the fontoxpath is discussed?

Thanks a lot for this wonderful tool.

**Comment by DrRataplan** [comment]
Hi, Thanks!

I agree documentation is a bit sparse, leaning to non-existant. Sorry about that! FontoXPath started as a 20% project here at [Fonto](https://www.fontoxml.com/), and it is mainly developed over here, at Fonto. Most communication happens over here as well, using an internal board. For external communication with non-Fonto devs, we use GitHub issues. Would you have any advice on what we can do more?

To answer your question about adding functions, we usually start by going over already-implemented functions.
Let's say we're going to implement something like `fn:contains-token#2` (https://www.w3.org/TR/xpath-functions-31/#func-contains-token) (note that collations are not implemented yet, so ignore the 3 arguments version). 

We'll need to start by adding the function definition at the end of the [builtInFunctions.string.ts]( https://github.com/FontoXML/fontoxpath/blob/master/src/expressions/functions/builtInFunctions.string.ts) file.
The first challenge would be to extract the 'actual' values from the lazy-evaluation iterator/generator-based arguments you would be getting in the function you've just created. A common pattern in FontoXPath is a function `next()` that returns one of three values: `{done: false, value: {type: <type>, value: <actual value>}}`, `{done: true}`, or `{ready: false, promise: Promise<undefined>}`. The first two values are vanilla iterators, but the third is different. FontoXPath is working towards an async implementation to prepare for doing things like a step-through debugger that can pause on a certain 'step', so that introduces additional complexity. These iterators are usually contained in an `ISequence`.
To make these iterators and sequences easier to work with, we've built several higher-order functions, like `mapAll` (get ALL values from an iterator, call the callback, and return an iterator over the return of the callback. Or Filter, which filters using a callback. See the `ISequence` class for more.

For the contains-token function, I'd use `ISequence#mapAll` for the first argument (we're going to need all of them anyway). This accepts a callback in which we can return another sequence. In this callback, I'd return the result of the mapAll function over the second argument.

This should look something like this:

```
function fnContainsToken (_dynamicContext, _executionParameters, _staticContext, inputSequence, tokenSequence) {
  return inputSequence.mapAll(inputs => tokenSequence.mapAll([token] => {
    // TODO: normalize whitespaces of input, see whether token can be found, etcetera.
}
}
```

Now comes the fun stuff, implementing the spec. I'll leave that open for now.

I'll make sure this will be included in the internal documentation.

Thanks for showing interest! I hope this answers your questions! Please let me know if I can help you in any other way!

**Comment by JoernT** [comment]
Wow - thanks for the  quick reply. Guess i need a bit to chew that in.

Also thanks for giving a bit of background. So now for my interest in Fontoxpath: i'm a frontend guy over here at the eXist-db project. I've ran open source projects since 2001 (Chiba, betterFORM) which were centered around implementation of W3C XForms. This had not the success it probably deserved and i joined the eXist-db team and work from day to day with the product. betterFORM is not compatible with latest eXist-db and therefore we're working on a new, modernized forms framework along the lines of XForms 2. For many years there has been no option for XPath in the browser beyond version 1.0. (Saxon-js not being an option as it's not open source - sorry Michael)

So i'm exited to have stumbled across your impressing implementation (qudos to the team). After first quick tests it feels like fontoxpath actually offers a new perspective for an implemenation. Up to now we've always favored a server-driven approach where all serious work was done in Java with Saxon. 

The primary goal of the forms framework is to allow seemless XML editing (with some JSON support) for the more structured XML languages along with advanced validation (datatyping, dependencies, calculations). For maximum durability we use Web Components as implementation platform. 

Regarding communication - it would already help a lot to add a remark to the readme that states how you expect people to get in contact (use github issues for you). eXist-db still uses a classical mailinglist and a slack channel everybody can join. However i understand that still creates a bit of work and somebody must be willing/able to do that (answering people). As reactive as you was github issues are also fine for me. 

What's great about fontoxpath:
- looks quite clean in the code though i'm unfortunately not a typescript guy but yeah i can use it
- great test suite (i know how much work that takes)
- XQuery support (though not that important to me personally)
- access to the AST (very! useful)
- performs well at least within the scope that interests me 

What's probably improveable:
- docs ;) 
- why not offer as ES6 module? Had to reach out to rollup.js to convert before i could start. In Web Components world everything now is ES6 and i like it. 

Thanks for taking the time - i guess we could find a lot more to talk about as i feel that fonto and eXist-db have quite some overlap in expertise and technical interest. 

I probably come back to nag you with detail question should i move along (so many considerations and projects to be done ;)
