### ISSUE TITLE
xQuery FLOWR Expression

### ISSUE THREAD

**Issue by steven-so** [FontoXML/fontoxpath#292]
Hello, I'm trying to get an xQuery expression to work using the FLOWR example from the Playground. 

```javascript
const { evaluateXPath } = require("fontoxpath");
const jsdom = require("jsdom");
const { JSDOM } = jsdom;

const dom = new JSDOM("");
const DOMParser = dom.window.DOMParser;
const parser = new DOMParser();
const documentNode = parser.parseFromString(
  `<bookstore>
  <book category="COOKING">
    <title lang="en">Everyday Italian</title>
    <author>Giada De Laurentiis</author>
    <year>2005</year>
    <price>30.00</price>
  </book>
  <book category="CHILDREN">
    <title lang="en">Harry Potter</title>
    <author>J K. Rowling</author>
    <year>2005</year>
    <price>29.99</price>
  </book>
  <book category="WEB">
    <title lang="en">XQuery Kick Start</title>
    <author>James McGovern</author>
    <author>Per Bothner</author>
    <author>Kurt Cagle</author>
    <author>James Linn</author>
    <author>Vaidyanathan Nagarajan</author>
    <year>2003</year>
    <price>49.99</price>
  </book>
  <book category="WEB">
    <title lang="en">Learning XML</title>
    <author>Erik T. Ray</author>
    <year>2003</year>
    <price>39.95</price>
  </book>
</bookstore>`,
  "text/xml"
);

console.log(
  evaluateXPath(
    "for $x in /bookstore/book where $x/price>30 return $x/title",
    documentNode,
    null,
    null,
    null,
    {
      language: evaluateXPath.XQUERY_3_1_LANGUAGE,
    }
  )
);

```
Expected result: 
<title lang="en">XQuery Kick Start</title>
<title lang="en">Learning XML</title>

My result:
[ Element {}, Element {} ]

If I use "evaluateXPathToString()" instead of "evaluateXPath()" I get the error: "Error: XPST0003: Use of XQuery FLWOR expressions in XPath is no allowed." 

Sorry if this is something stupid on my part. Any help would be greatly appreciated!

**Comment by DrRataplan** [comment]
Hey there!

In FontoXPath, we tend to return instances of Nodes. `console.log` does not output them nicely: hence the `[Element {}, Element {}]`.

Could you verify whether this works as you expect it?

```javascript
console.log(
  evaluateXPath(
    "for $x in /bookstore/book where $x/price>30 return $x/title",
    documentNode,
    null,
    null,
    null,
    {
      language: evaluateXPath.XQUERY_3_1_LANGUAGE,
    }
  ).map(element=>element.outerHTML)
);
```

The `evaluateXPathToString()` should work, but in order to work, one of the optional `null` arguments from the original call should be removed. `evaluateXPathToString` does not require the `type` argument `evaluateXPath` accepts. Not that `evaluateXPathToString` is what you want though: it would stringify the result: return the text content of the elements.

I think you'll want to work with those Node instances though. XML is just a string serialization of a DOM. The DOM is what XPath works with. Besides that, I always advice to use `evaluateXPathToNodes` if you always know you are returning nodes from your expression, as opposed to booleans. It's just more predictable.

Feel free to reach out if I can help you any further.

Regards,

Martin

**Comment by steven-so** [comment]
Thank you Martin! That worked perfectly. 

Thanks for your excellent explanation and work on fontoxpath. This is a huge help!

**Comment by DrRataplan** [comment]
Hi Steven,

Awesome! Thanks!

I'll go ahead and close the issue. If I can assist you in any other way, reach out!

Regards,

Martin
