### ISSUE TITLE
Return type cardinality error on custom function in IE11

### ISSUE THREAD

**Issue by ymor** [FontoXML/fontoxpath#302]
Hi,
We've come across an issue when upgrading from 3.14.2 to 3.15.0 when using a custom function.

Here's a really contrived example that I've tried to make a simple as possible: https://github.com/ymor/fonto-ie11  

If you run it in chrome/firefox, you will see the react logo. However if you use IE11 you will get the following error:
`XPTY0004: Multiplicity of function return value of type item() for my-function is incorrect. Expected exactly one`
I had a play around with the cardinality of the return type and it appears that fontoxpath thinks that the custom function is returning an empty sequence when running in IE11.  My assumption is that it's to do with the `createTypedValueFactory` that was added in 3.15.0. 

It is worth noting it still errors in the latest release. I was just trying to narrow it down to the release where it broke.
Also I'm not sure what your official stance is on supporting IE.  But I would really appreciate if you could support it for a little while longer :) 

Let me know if you have any further questions or have issues getting the repo running.
Thanks.

**Comment by DrRataplan** [comment]
Oh no, IE11. I do not see a reason why FontoXPath can not support it. As
long as you get the proper polyfills, use all the Babel transpilation, and
do not use the plain broken built-in DOM implementation, it should just
work. We do not support IE11 ourselves for Fonto Editor, this has various
reasons, mainly bugs and it being EOL.

I will give this a look this week, I'll have to get my IE 11 testing VM
dusted off again. I'll assume this error does not occur in the legacy Edge
compatibility mode?

Gut feeling tells me this broke because we started to use symbols to
identify values created by fontoxpath, with that typedvaluefactory. I think
I know a way to work around this. I will try to fix it. I can not promise
any full support in the future though. We at Fonto do not test for IE 11.
New releases may introduce new breakage. We will try our best to help any
users that still need to support Internet Explorer 11, but only within
reason.

I sincerely sympathize with you in supporting IE11.

Regards,

Martin

**Comment by ymor** [comment]
Unfortunately IE11 is still widely used within the NHS in the UK! 

The error does also occur in Edge Internet Explorer mode.  We do include the following as a polyfill for symbol: https://github.com/facebook/create-react-app/blob/master/packages/react-app-polyfill/README.md which basically just imports the polyfill from corejs.

Thanks for taking a look and we will obviously accept the risks of us using fontoxpath in IE11.

**Comment by DrRataplan** [comment]
Found it.

We are using the `in` operator to detect whether a symbol we've created exists on some object passed from the outside. One of the polyfills declares _all_ symbols ever used on the `Object`. Which breaks the working of the `in` operator.

I'll make a proper fix sometime soon. This week and next are our QA weeks for the upcoming 7.14 version of Fonto, so forgive me if I do not get to it this week or the next.

For future reference, the code is src/registerCustomXPathFunction.ts, line 135-ish.

Regards,

Martin

**Comment by ymor** [comment]
Ah I see. I can have a look at submitting a PR this weekend/early next week.  From a quick test external to fontoxpath, something like `Object.getOwnPropertySymbols(jsResult).includes(IS_XPATH_VALUE_SYMBOL)` should do the job.  

Again thanks for taking a look :)

**Comment by DrRataplan** [comment]
I just release 3.17.3, which fixes this issue!
