### ISSUE TITLE
Issue serializing sequences that are members of an array

### ISSUE THREAD

**Issue by line-o** [FontoXML/fontoxpath#315]
Evaluating any of the following in FontoXPath

```xquery
[(1,2)]
```

```xquery
[[1,2]?*]
```

```xquery
array:append([],  (1,2))
```
*Expected*

Evaluates to an array with a sequence; `[(1,2)]`  

*Actual*

Returns an error
"Serialization error: The value of an entry in an array is expected to be a singleton sequence."

Testlink:

https://xpath.playground.fontoxml.com/?mode=1&variables=%7B%7D&xml=%3Croot%2F%3E&xpath=%28%3A+-+sequence+items+will+become+individual+members+-+%3A%29%0Aarray%7B%281%2C+2%29%7D%2C%0Aarray%7B%5B%281%2C+2%29%5D%3F*%7D%2C%0A%28%3A+construct+an+array+with+a+sequence+as+a+member+%5B%281%2C2%29%5D+%3A%29%0A%5B%281%2C2%29%5D%2C%0A%5B%5B%281%2C+2%29%5D%3F*%5D%2C%0Aarray%3Aappend%28%5B%5D%2C+%281%2C2%29%29%0A&context=

It may even be represented correctly in the AST but cannot be serialised.

**Comment by line-o** [comment]
`[(1,2)]?1`

**Comment by DrRataplan** [comment]
Hey there, 

Sorry for the late reaction.

I actually expected this error in this case. When I first built array support, I ran into the issue that all JavaScript JSON structures can be transformed to maps and arrays, but not always back. Especially not lossless. In this case, to transform `[(1,2)]` to a JavaScript counterpart, we have five options:

 - Output `[1,2]`, which is wrong because the array changes size
 - Output `[[1,2]]`, which is wrong because the XPath version had _one_ array. Also, `[1]` outputs `[1]`, not `[[1]]`, so that would be very odd.
 - Output `['1 2']`, which is wrong because the input was two decimals.
 - Expose the XPath data structure to the outside, expose the sequences, arrays and the full type system. This makes the XPath engine significantly harder to 'just use'.
 - Throw an error when we output an array with an item with an entry with more than one item. Have developers work around the conversion by outputting JSON-compatible maps and arrays.

Of these options, only the throwing is not wrong per se.

Agreed, the error could be better. I'll improve it.

Regards,

Martin

**Comment by line-o** [comment]
I agree @DrRataplan, changing the error message would already help a lot.

About the serialisation options from XDM sequences -> JSON:

- You could add a global serialisation option to convert all sequences to arrays. This would make it much easier to play around with some XPaths as they usually return sequences. 
- Another options would be to serialise them to special objects: something along the lines of `{"type": "sequence", "items": [1, 2, "foo", true, [], {}]}`

**Comment by DrRataplan** [comment]
I improved the error message a bit, It was lying a bit since non-singleton sequences are sometimes valid (in the case of the empty sequence, which is converted to `null`). 

While I like your suggestion for a more raw output format, I am afraid it will get too explicit too fast. I will keep it in the back of my mind though because it might be very valuable in the playground. I hope no one will want to process it in their own production application that depends on FontoXPath.

I'll close this issue when the error messages PR is integrated. Thanks for bringing this to our attention!

Regards,

Martin

**Comment by line-o** [comment]
Thanks for taking it into consideration. I understand that it might be out of scope and there is a valid way to get there by explicitly wrapping a sequence in either `array {}` or `[]` depending on the desired output.
