### ISSUE TITLE
Request: Remove usage of Function() to load the XPathParser_raw

### ISSUE THREAD

**Issue by ymor** [FontoXML/fontoxpath#326]
We use fontoxpath in the browser and due to the use of Function when loading the generated XPath Parser we have to set `unsafe-eval` on our script sources CSP, which isn't particularly ideal.

Is it possible for the generated parser to be built and imported in a more standard way?
Thanks.

**Comment by DrRataplan** [comment]
Hey @ymor,

We have that `new Function` shenanigan because of historic reasons. This repo used to be a pure Closure Compiler project which, at the time, had no way of disabling the compiler for specific files. So we had to resort to evaluating a string, yadayadayada

Now that we use TypeScript, there exists the `// @ts-ignore` flag, which does work.

I gave this another try, and it worked. Furthermore, I saw a 10kB reduction in the overall filesize of the esm bundle of FontoXPath: 385kB -> 375kB, which is imho pretty significant. It also removes the dependency on uglifyJS, which is admirable in itself!

Thanks for pointing this out!

Regards,

Martin

**Comment by DrRataplan** [comment]
Fix is being tracked in #330

**Comment by DrRataplan** [comment]
I just integrated the PR. I'm making a new release right now.

**Comment by ymor** [comment]
Nice one, Thank you very much for this!

**Comment by DrRataplan** [comment]
`npm i fontoxpath@3.17.4` :tada:
