### ISSUE TITLE
Ordering from './/' descendant selector is wrong and different then 'descendant::'

### ISSUE THREAD

**Issue by EvadeHaas** [FontoXML/fontoxpath#36]
https://xpath.playground.fontoxml.com/?xml=%3Cref+id%3D%22bib12%22%3E%3Cmixed-citation+publication-type%3D%22journal%22%3E%3C%3FAuthorQuery+id%3D%22Q14%22+queryText%3D%22CrossRef+reports+the+DOI+should+be+%26quot%3B10.1175%2F1520-0477%281986%29067%26lt%3B1226%3ASCOPMM%26gt%3B2.0.CO%3B2%26quot%3B%2C+not+%26quot%3B10.1175%2F1520-0477%281986%29067%2C1226%3ASCOPMM.2.0.CO%3B2%26quot%3B.+eXtyles+has+used+the+CrossRef-supplied+DOI.+%28Ref.+%26quot%3BWilheit%2C+1986%26quot%3B%29%22%3F%3E%3Cperson-group+person-group-type%3D%22author%22%3E%3Cstring-name%3E%3Csurname%3EWilheit%3C%2Fsurname%3E%2C+%3Cgiven-names%3ET.+T.%3C%2Fgiven-names%3E%3C%2Fstring-name%3E%3C%2Fperson-group%3E%2C+%3Cyear%3E1986%3C%2Fyear%3E%3A+%3Carticle-title%3ESome+comments+on+passive+microwave+measurement+of+rain.%3C%2Farticle-title%3E+%3Csource%3EBull.+Amer.+Meteor.+Soc.%3C%2Fsource%3E%2C+%3Cvolume%3E67%3C%2Fvolume%3E%2C+%3Cfpage%3E1226%3C%2Ffpage%3E%E2%80%93%3Clpage%3E1232%3C%2Flpage%3E%2C+doi%3A%3Cpub-id+pub-id-type%3D%22doi%22%3E10.1175%2F1520-0477%281986%29067%26lt%3B1226%3ASCOPMM%26gt%3B2.0.CO%3B2%3C%2Fpub-id%3E%3C%2Fmixed-citation%3E%3C%2Fref%3E&xpath=string-join%28%2F%2Ftext%28%29%29+%3D+string-join%28descendant%3A%3Atext%28%29%29

**Comment by DrRataplan** [comment]
Thanks for the issue!

It seems like the sorting defined in PathSelector has an error. This sorting is spread out to different implementations, which get chosen in different contexts. The one it chooses here is in the case of a set of locally sorted sequences. It erroneously assumes that the first item it gets is the first it can return.

We should instead sort the sequences given to mergeSortedSequences. We can still use the sortedness of the separate sequences.

In the meantime, you could just use `descendant::text()` instead of `//text()`.
