### ISSUE TITLE
Unable to return xs:date or xs:datetime from a custom xpath function

### ISSUE THREAD

**Issue by ymor** [FontoXML/fontoxpath#38]
If you register a custom function that returns an xs:date or xs:datetime, you receive the following error at runtime:

> `Values of the type "${type}" can not be adapted to equivalent XPath values.`

Would it be possible to update the case statement to allow dates and datetimes to be returned from custom functions?
Thanks.

**Comment by DrRataplan** [comment]
Hi Mark,

That does sound like some irritating behaviour that should be fixed. I
remember that the datetime implementation already has a way to convert to a
JavaScript date, updating the switch with an extra case for a number of
date/time types shouldn't be too difficult.

Unfortunately, I am abroad for a couple of weeks🌴 and I do not have my
laptop with me. This does seem like a perfect first pull-request (hint,
hint). Could I ask you to help with this? This should also be a good test
for the contribution guide I wrote a while ago.
I should be able to orchestrate an npm publish from remote, so that we can
integrate it.

Greetings from Italy,

Martin

**Comment by ymor** [comment]
Hi Martin,
No worries always happy to help.  I did have a few issues getting the build/tests running on windows.  But I've managed to solve them and hopefully the fix will work on all platforms.  

But now I am having problems with the QT3 tests causing Firefox and Chrome to look like its frozen around the 31% mark.  Is it just a matter of leaving it for a while until it has finished? I have a fairly decent spec laptop:  i7-6820HQ 2.7ghz and 32GB of RAM.  

Hope your having a good holiday.  Also please don't feel like you need to respond to this until your back!
Thanks.

**Comment by DrRataplan** [comment]
Hi Mark,

Yeah, the QT3 tests can take a while, but usually not more than like 10
minutes. I've found that focussing the browser and keeping it focussed
helps a lot.

I'd recommend using the 'normal' tests for developing, and switching to the
QT3 tests as a final check.

Thanks for the help!

Martin

**Comment by DrRataplan** [comment]
Hi Mark,

I've just published a new version of FontoXPath :tada:. Thanks again for your help!

Martin
