### ISSUE TITLE
Possible to find document location of query results?

### ISSUE THREAD

**Issue by rrthomas** [FontoXML/fontoxpath#447]
The nodes returned by a query have their `parentElement` (where applicable) set to `null`. Is there a way to discover where the nodes came from in the queried document? Sorry if I've overlooked something obvious!

**Comment by DrRataplan** [comment]
Hello there!

That can only be when you are creating clones of nodes. Is this related to that `copy-modify-return` question? In there, you are creating new nodes (the `copy` part of `copy-modify-return`). Because FontoXPath's XQuery Update Facility is pure, functional and side-effect-free, it can not change the document before you tell it so (using the `executePendingUpdateList` function). 

Does that make sense?

Regards,

Martin

**Comment by rrthomas** [comment]
Aha! I think I may have worked out what was going wrong, thanks for the hint. I shall investigate and report back.

**Comment by rrthomas** [comment]
What happened in my case was that I was running a query on an XML literal (i.e. not part of the document), and the query happened to match the entire literal, and so the element returned did not have a parent. Closing.
