### ISSUE TITLE
Incorrect value from calculation

### ISSUE THREAD

**Issue by ymor** [FontoXML/fontoxpath#54]
Hi,
The below example is returning the incorrect value. 
https://xpath.playground.fontoxml.com/?xml=&xpath=5+-+1+-+1

**Expected value**
3

**Actual value**
5

It seems to be doing 5 - (1 - 1)  instead?

**Comment by DrRataplan** [comment]
Yup, it's a parser fault. I would expect this to fail somewhere in the QT3 test set.

We are working on a re-implementation of the parser; I will pay extra attention to this part. I expect this to be done somewhere this month (we are moving to an XQueryX based parser so that we have more room for static optimizations / constant folding).

If this is blocking you in any way, I should be able to fix this in the current parser.

**Comment by ymor** [comment]
If you could take a look at fixing the current parser that would be appreciated. If I get any free time this week, I'll try and take a quick look too.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by DrRataplan** [comment]
If I can get some time to work on this, I'll fix it in the current parser. It shouldn't be too hard. If you're able to have a look, that would be awesome!

The bug is in the grammar: I tried to be smart and work around the difficulty regarding addition and subtraction. Obviously that didn't work... [This code can be found in the pegjs file around line 124](https://github.com/FontoXML/fontoxpath/blob/master/src/parsing/xpath.pegjs#L124).

Here, we effectively make a tree of the repetition of binary operators (`'+'/'-'`) by recursing on the right hand side. This makes the tree lean to the right hand side, which is wrong. Because it is impossible to do left-hand-side recursion in a PEG grammar, this makes it a nice challenge. If you're interested in the background of why left recursion is a problem, [this is a nice read](https://pdos.csail.mit.edu/papers/parsing:popl04.pdf).

I'd flatten out the operator 'tree' first, keep track of the operator, and use a normal reduce/fold-left to build up the correct tree: `5 - 1 - 1` -> `(5 (- 1) (- 1))` -> `(- (- 5 1) 1)`.

BTW: The unit tests are executed a bit differently from before. We removed the browser-based karma tests in favour of plain mocha in Node. We've updated the CONTRIBUTING.md file accordingly.
