### ISSUE TITLE
xs:decimal stringification may cause scientific notation

### ISSUE THREAD

**Issue by DrRataplan** [FontoXML/fontoxpath#78]
https://xpath.playground.fontoxml.com/?mode=0&variables=%7B%7D&xml=%3Cxml%3E%0A%3C%2Fxml%3E&xpath=xs%3Adecimal%28%27100000000000000000000000000000%27%29+%3D%3E+xs%3Astring%28%29

xs:decimals do not allow exponents.

**Comment by JosVerburg** [comment]
I think the problem is that we now get the result from JavaScript which is not compliant to the XQuery spec. Under [19.1.1 Casting to xs:string and xs:untypedAtomic](https://www.w3.org/TR/xpath-functions-31/#casting-to-string) it states for xs:decimal to xs:string
"Otherwise, the canonical lexical representation of SV is returned, as defined in [XML Schema Part 2: Datatypes Second Edition]."
And which in turn [doesn't specify that it allows the scientific notation](https://www.w3.org/TR/xmlschema-2/#decimal).

**Comment by DrRataplan** [comment]
This has been dead for a while now w/o anyone running into this. I'm closing it
